# Generated by Django 2.2.6 on 2021-02-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OraDbInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('ip_addr', models.CharField(max_length=100)),
                ('port_num', models.IntegerField()),
                ('srv_name', models.CharField(max_length=20)),
                ('inst_name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('awr_enabled', models.BooleanField(default=False)),
                ('insp_enabled', models.BooleanField(default=False)),
                ('logmon_enabled', models.BooleanField(default=False)),
                ('tsmon_enabled', models.BooleanField(default=False)),
                ('asmmon_enabled', models.BooleanField(default=False)),
                ('production', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('ip_addr', 'port_num', 'inst_name')},
            },
        ),
    ]
